import type { Metadata } from "next";
import { Gideon_Roman } from "next/font/google";

import SmoothScroll from "@/app/components/SmoothScroll";
import "./fonts.css";
import "./globals.css";
import Header from "@/app/components/Header";

const gideonRoman = Gideon_Roman({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gideon",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gideonRoman.variable} ${gideonRoman.className} antialiased font-sans`}
    >
      <head>
        <link
          rel="preload"
          href="/font/1797.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <SmoothScroll>
          <Header />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
