import type { Metadata } from "next";
import { Gideon_Roman } from "next/font/google";

import "./globals.css";
import Header from "@/app/components/Header";

const gideonRoman = Gideon_Roman({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gideon",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gideonRoman.variable} ${gideonRoman.className} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
